###############################################################
#####         Configurações comuns a todos perfis        ######
###############################################################

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false

Server:
  servlet:
    context-path: /consumer

---
###############################################################
#####            Configurações ambiente local            ######
###############################################################

spring:
  config:
    activate:
      on-profile: develop

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 1
      data-source-properties:
        cachePrepStmts: false

server:
  port: 8085
---